language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install: 
  - "pip install -r requirements-testing.txt --use-mirrors"
  - "pip install coveralls"
  - "python setup.py install"
script: 
  nosetests --with-coverage --cover-package=frecency
after_success:
  coveralls
